#!/usr/bin/env bash

lookup_text=${1:-}

if [ ! -n "$lookup_text" ]; then
    echo "[Usage]"
    echo "lookfor TEXT in COMMAND"
    echo "[Example]"
    echo "lookfor chrome in ps -A"
    exit
fi

lookup_option=$2 # 'in' for now

lookup_command=${@:3}

echo 'Looking for '$lookup_text' in '$lookup_command

$lookup_command | grep -i $lookup_text

